[package]
name = "serde-context"
version = "0.1.0"
edition = "2021"
description = "Contextual serialization with serde"

[dependencies]
serde = { version = "1.0.215" }
serde-context-derive = { path = "../serde-context-derive", optional = true }

[features]
derive = ["serde-context-derive"]
